pipeline {​​​​​​
    agent any

    stages {​​​​​​
        stage ('Compile Stage') {​​​​​​

            steps {​​​​​​
                sh '''
            cd StudentsDetails
            mvn clean install
        '''
            }​​​​​​
        }​​​​​​
    }​​​​​​
    ​​​​​​
}​​​​​​