pipeline {
agent any
stages {
stage ('Build Stage') {
steps {
sh '''
cd StudentsDetails
mvn clean install
'''
}
}
stage ('Test Stage') {
steps {
junit 'StudentsDetails/target/surefire-reports/*.xml'
}
}
}
}
            ​​​​​​ ​​​​​​
​​​​​​