pipeline{
	agent any
	
	stages{
		stage('Compile Stage'){
			steps{
				
					sh '''
          cd StudentsDetails
          mvn clean install
    '''
		    }
	    }
	
	
	    
		stage('Test Stage'){
			steps{
				
					sh '''
          cd StudentsDetails
          mvn clean install sonar:sonar
    '''
		    }
	    }
	 }
}     ​​​​​​ ​​​​​​
​​​​​​